[2025-08-03T10:37:01.835+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:37:01.836+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:37:01.880+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:37:01.881+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:37:01.920+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:36:00+00:00 [queued]>
[2025-08-03T10:37:01.931+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:36:00+00:00 [queued]>
[2025-08-03T10:37:01.932+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:37:01.947+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:36:00+00:00
[2025-08-03T10:37:01.959+0000] {standard_task_runner.py:57} INFO - Started process 520 to run task
[2025-08-03T10:37:01.964+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:36:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpfvg_y8n_']
[2025-08-03T10:37:01.969+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask fetch_training_data
[2025-08-03T10:37:02.044+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:37:02.045+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:36:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:37:02.048+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:36:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:37:02.162+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:36:00+00:00'
[2025-08-03T10:37:02.174+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:37:03.248+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100552  155992    461  ...    product_A 2025-08-03 10:36:21.296951
100553  155993    555  ...    product_A 2025-08-03 10:36:31.098152
100554  155994    278  ...    product_A 2025-08-03 10:36:41.114794
100555  155995    276  ...    product_A 2025-08-03 10:36:51.133298
100556  155996    100  ...    product_A 2025-08-03 10:37:00.948258

[5 rows x 12 columns]
[2025-08-03T10:37:03.281+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:37:03.314+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T103600, start_date=20250803T103701, end_date=20250803T103703
[2025-08-03T10:37:03.386+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:37:03.421+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
