[2025-08-03T10:29:01.566+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:29:01.567+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:29:01.603+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:29:01.604+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:29:01.643+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:28:00+00:00 [queued]>
[2025-08-03T10:29:01.654+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:28:00+00:00 [queued]>
[2025-08-03T10:29:01.655+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:29:01.673+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:28:00+00:00
[2025-08-03T10:29:01.683+0000] {standard_task_runner.py:57} INFO - Started process 283 to run task
[2025-08-03T10:29:01.690+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:28:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpg_n7_jgg']
[2025-08-03T10:29:01.697+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask fetch_training_data
[2025-08-03T10:29:01.763+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:29:01.764+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:28:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:29:01.766+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:28:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:29:01.866+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:28:00+00:00'
[2025-08-03T10:29:01.877+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:29:02.786+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100503  155943    419  ...    product_A 2025-08-03 10:28:13.904160
100504  155944    420  ...    product_A 2025-08-03 10:28:23.927926
100505  155945    421  ...    product_A 2025-08-03 10:28:34.028224
100506  155946    422  ...    product_A 2025-08-03 10:28:44.041362
100507  155947    423  ...    product_A 2025-08-03 10:28:54.056623

[5 rows x 12 columns]
[2025-08-03T10:29:02.825+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:29:02.858+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T102800, start_date=20250803T102901, end_date=20250803T102902
[2025-08-03T10:29:02.908+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:29:02.935+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
