[2025-08-03T10:35:01.252+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:35:01.253+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:35:01.298+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:35:01.300+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:35:01.346+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:34:00+00:00 [queued]>
[2025-08-03T10:35:01.361+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:34:00+00:00 [queued]>
[2025-08-03T10:35:01.361+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:35:01.380+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:34:00+00:00
[2025-08-03T10:35:01.391+0000] {standard_task_runner.py:57} INFO - Started process 458 to run task
[2025-08-03T10:35:01.395+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:34:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp4m46sjr6']
[2025-08-03T10:35:01.399+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask fetch_training_data
[2025-08-03T10:35:01.469+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:35:01.470+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:34:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:35:01.472+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:34:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:35:01.586+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:34:00+00:00'
[2025-08-03T10:35:01.601+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:35:02.625+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100540  155980    456  ...    product_A 2025-08-03 10:34:21.936055
100541  155981    457  ...    product_A 2025-08-03 10:34:31.749973
100542  155982    458  ...    product_A 2025-08-03 10:34:41.766578
100543  155983    459  ...    product_A 2025-08-03 10:34:51.776349
100544  155984    452  ...    product_A 2025-08-03 10:35:01.570175

[5 rows x 12 columns]
[2025-08-03T10:35:02.658+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:35:02.694+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T103400, start_date=20250803T103501, end_date=20250803T103502
[2025-08-03T10:35:02.775+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:35:02.806+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
