[2025-09-21T11:10:02.464+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:10:02.465+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:10:02.535+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:10:02.537+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:10:02.605+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:09:00+00:00 [queued]>
[2025-09-21T11:10:02.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:09:00+00:00 [queued]>
[2025-09-21T11:10:02.627+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:10:02.655+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-09-21 11:09:00+00:00
[2025-09-21T11:10:02.678+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2025-09-21T11:10:02.688+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-09-21T11:09:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp4m8zpppc']
[2025-09-21T11:10:02.696+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask fetch_training_data
[2025-09-21T11:10:02.842+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:10:02.844+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:09:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:10:02.847+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:09:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:10:03.102+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:09:00+00:00'
[2025-09-21T11:10:03.121+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-09-21T11:10:04.724+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100502  155942    478  ...    product_A 2025-09-21 11:09:21.105955
100503  155943    477  ...    product_A 2025-09-21 11:09:32.039511
100504  155944    476  ...    product_A 2025-09-21 11:09:42.050871
100505  155945    475  ...    product_A 2025-09-21 11:09:52.057827
100506  155946    474  ...    product_A 2025-09-21 11:10:02.887304

[5 rows x 12 columns]
[2025-09-21T11:10:04.805+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-06-23', 'end_date': '2025-09-21'}
[2025-09-21T11:10:04.894+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250921T110900, start_date=20250921T111002, end_date=20250921T111004
[2025-09-21T11:10:05.036+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:10:05.089+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
